version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      maven:
        patterns:
          - "*maven*plugin*"
          - "*plexus*"
          - "org.apache.maven*:*"
