version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      maven:
        patterns:
          - "*maven*plugin*"
          - "*plexus*"
          - "org.apache.maven*:*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      workflow-actions:
        patterns:
          - "*"
    allow:
      - dependency-name: "actions/*"
      - dependency-name: "redhat-actions/*"
